# Generated by Django 5.1 on 2024-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image_url',
            field=models.JSONField(default=list),
        ),
    ]
