# Generated by Django 5.1 on 2024-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cars_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
