# Generated by Django 5.1 on 2024-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_cars_price_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='comparations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cars',
            name='show_image',
            field=models.CharField(default='No image available', max_length=300),
        ),
    ]
